-- LexPro PostgreSQL schema
-- Flyway source: DBM/lexpro_schema_postgresql.sql
-- Source SHA-256: E1071691735EB243F6CE93D72B314AC7A218CC4DB06DFA2C007340F9A994CCBA
-- Flyway owns the transaction; only the source file's outer BEGIN/COMMIT are omitted.
-- Target: PostgreSQL 15+ and pgvector
-- Encoding: UTF-8
--
-- Prerequisite:
--   Install pgvector on the PostgreSQL server before running this script.
--
-- Run example:
--   psql -v ON_ERROR_STOP=1 -d lexpro -f lexpro_schema_postgresql.sql

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE SCHEMA IF NOT EXISTS lexpro;

SET search_path TO lexpro, public;

CREATE OR REPLACE FUNCTION lexpro.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- 1. Users and cases
-- -----------------------------------------------------------------------------

CREATE TABLE app_user (
    user_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           varchar(100) NOT NULL,
    password_hash      varchar(255) NOT NULL,
    real_name          varchar(100) NOT NULL,
    role               varchar(30) NOT NULL DEFAULT 'USER',
    permissions_json   jsonb NOT NULL DEFAULT '{}'::jsonb,
    case_scope         jsonb NOT NULL DEFAULT '{}'::jsonb,
    status             varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_app_user_username_not_blank
        CHECK (btrim(username) <> ''),
    CONSTRAINT ck_app_user_password_hash_not_blank
        CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_app_user_role
        CHECK (role IN ('ADMIN', 'USER')),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_app_user_permissions_object
        CHECK (jsonb_typeof(permissions_json) = 'object'),
    CONSTRAINT ck_app_user_case_scope_object
        CHECK (jsonb_typeof(case_scope) = 'object')
);

CREATE UNIQUE INDEX ux_app_user_username_lower
    ON app_user (lower(username));

CREATE TRIGGER trg_app_user_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE case_record (
    case_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name          varchar(255) NOT NULL,
    case_no            varchar(100),
    case_type          varchar(50) NOT NULL,
    case_cause         varchar(255),
    prosecutor_id      bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    creator_id         bigint NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    accept_date        date,
    deadline_date      date,
    case_status        varchar(30) NOT NULL DEFAULT 'PENDING',
    created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_case_record_name_not_blank
        CHECK (btrim(case_name) <> ''),
    CONSTRAINT ck_case_record_type_not_blank
        CHECK (btrim(case_type) <> ''),
    CONSTRAINT ck_case_record_status
        CHECK (case_status IN ('PENDING', 'PROCESSING', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_case_record_dates
        CHECK (deadline_date IS NULL OR accept_date IS NULL OR deadline_date >= accept_date)
);

CREATE UNIQUE INDEX ux_case_record_case_no
    ON case_record (case_no)
    WHERE case_no IS NOT NULL;

CREATE INDEX ix_case_record_creator_id ON case_record (creator_id);
CREATE INDEX ix_case_record_prosecutor_id ON case_record (prosecutor_id);
CREATE INDEX ix_case_record_status ON case_record (case_status);
CREATE INDEX ix_case_record_accept_date ON case_record (accept_date);

CREATE TRIGGER trg_case_record_updated_at
BEFORE UPDATE ON case_record
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE case_party (
    party_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    party_name         varchar(255) NOT NULL,
    party_role         varchar(30) NOT NULL,
    party_type         varchar(30) NOT NULL,
    identity_type      varchar(30),
    identity_number    varchar(100),
    gender             varchar(20),
    age                integer,
    description        text,
    created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_case_party_name_not_blank
        CHECK (btrim(party_name) <> ''),
    CONSTRAINT ck_case_party_role
        CHECK (party_role IN ('SUSPECT', 'VICTIM', 'WITNESS', 'OTHER')),
    CONSTRAINT ck_case_party_type
        CHECK (party_type IN ('PERSON', 'ORGANIZATION')),
    CONSTRAINT ck_case_party_age
        CHECK (age IS NULL OR age >= 0)
);

CREATE INDEX ix_case_party_case_id ON case_party (case_id);
CREATE INDEX ix_case_party_case_role ON case_party (case_id, party_role);

CREATE TRIGGER trg_case_party_updated_at
BEFORE UPDATE ON case_party
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE case_assignment (
    assignment_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    user_id            bigint NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    assignment_role    varchar(30) NOT NULL,
    is_current         boolean NOT NULL DEFAULT true,
    assigned_at        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at           timestamptz,

    CONSTRAINT ck_case_assignment_role
        CHECK (assignment_role IN ('PROSECUTOR', 'ASSIGNEE', 'REVIEWER')),
    CONSTRAINT ck_case_assignment_period
        CHECK (ended_at IS NULL OR ended_at >= assigned_at),
    CONSTRAINT ck_case_assignment_current_end
        CHECK (NOT is_current OR ended_at IS NULL)
);

CREATE UNIQUE INDEX ux_case_assignment_current
    ON case_assignment (case_id, user_id, assignment_role)
    WHERE is_current;

CREATE INDEX ix_case_assignment_case_id ON case_assignment (case_id);
CREATE INDEX ix_case_assignment_user_id ON case_assignment (user_id);

-- -----------------------------------------------------------------------------
-- 2. Evidence and document processing
-- -----------------------------------------------------------------------------

CREATE TABLE evidence_file (
    dossier_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    file_name          varchar(255) NOT NULL,
    file_type          varchar(100) NOT NULL,
    file_url           text NOT NULL,
    upload_user_id     bigint NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    uploaded_at        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_size          bigint,
    file_hash          varchar(128),
    parse_status       varchar(30) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT ck_evidence_file_name_not_blank
        CHECK (btrim(file_name) <> ''),
    CONSTRAINT ck_evidence_file_url_not_blank
        CHECK (btrim(file_url) <> ''),
    CONSTRAINT ck_evidence_file_size
        CHECK (file_size IS NULL OR file_size >= 0),
    CONSTRAINT ck_evidence_file_parse_status
        CHECK (parse_status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX ix_evidence_file_case_id ON evidence_file (case_id);
CREATE INDEX ix_evidence_file_upload_user_id ON evidence_file (upload_user_id);
CREATE INDEX ix_evidence_file_case_parse_status ON evidence_file (case_id, parse_status);
CREATE INDEX ix_evidence_file_case_hash ON evidence_file (case_id, file_hash)
    WHERE file_hash IS NOT NULL;

CREATE TABLE document_parse_result (
    doc_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id          bigint NOT NULL REFERENCES evidence_file(dossier_id) ON DELETE RESTRICT,
    version_no          integer NOT NULL,
    parse_status        varchar(30) NOT NULL DEFAULT 'PROCESSING',
    parsed_text_json    jsonb,
    raw_text            text,
    parser_version      varchar(100),
    error_message       text,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        timestamptz,

    CONSTRAINT ux_document_parse_result_version
        UNIQUE (dossier_id, version_no),
    CONSTRAINT ck_document_parse_result_version
        CHECK (version_no > 0),
    CONSTRAINT ck_document_parse_result_status
        CHECK (parse_status IN ('PROCESSING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_document_parse_result_completed_at
        CHECK (completed_at IS NULL OR completed_at >= created_at),
    CONSTRAINT ck_document_parse_result_success_content
        CHECK (parse_status <> 'SUCCESS' OR raw_text IS NOT NULL OR parsed_text_json IS NOT NULL),
    CONSTRAINT ck_document_parse_result_failed_error
        CHECK (parse_status <> 'FAILED' OR error_message IS NOT NULL)
);

CREATE INDEX ix_document_parse_result_dossier_id
    ON document_parse_result (dossier_id);
CREATE INDEX ix_document_parse_result_status
    ON document_parse_result (parse_status);

CREATE TABLE entity_result (
    entity_result_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id              bigint NOT NULL REFERENCES document_parse_result(doc_id) ON DELETE RESTRICT,
    entities_json       jsonb NOT NULL,
    model_name          varchar(100),
    model_version       varchar(100),
    prompt_version      varchar(100),
    schema_version      varchar(50),
    created_by          bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_entity_result_entities_array
        CHECK (jsonb_typeof(entities_json) IN ('array', 'object'))
);

CREATE INDEX ix_entity_result_doc_id ON entity_result (doc_id);
CREATE INDEX ix_entity_result_created_by ON entity_result (created_by);

CREATE TABLE legal_element_result (
    element_result_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id                  bigint NOT NULL REFERENCES document_parse_result(doc_id) ON DELETE RESTRICT,
    case_cause              varchar(255),
    raw_elements_json       jsonb NOT NULL,
    final_elements_json     jsonb,
    validation_report_json  jsonb,
    model_name              varchar(100),
    model_version           varchar(100),
    prompt_version          varchar(100),
    schema_version          varchar(50),
    created_by              bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_by            bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    confirmed_at            timestamptz,

    CONSTRAINT ck_legal_element_result_raw_json
        CHECK (jsonb_typeof(raw_elements_json) IN ('array', 'object')),
    CONSTRAINT ck_legal_element_result_confirmed
        CHECK ((confirmed_by IS NULL) = (confirmed_at IS NULL))
);

CREATE INDEX ix_legal_element_result_doc_id ON legal_element_result (doc_id);
CREATE INDEX ix_legal_element_result_created_by ON legal_element_result (created_by);

CREATE TABLE case_summary (
    summary_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    summary_type        varchar(30) NOT NULL,
    summary_text        text NOT NULL,
    model_name          varchar(100),
    model_version       varchar(100),
    prompt_version      varchar(100),
    is_current          boolean NOT NULL DEFAULT true,
    created_by          bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_case_summary_type
        CHECK (summary_type IN ('FACT', 'PROCESS', 'CONCLUSION', 'FULL')),
    CONSTRAINT ck_case_summary_text_not_blank
        CHECK (btrim(summary_text) <> '')
);

CREATE UNIQUE INDEX ux_case_summary_current
    ON case_summary (case_id, summary_type)
    WHERE is_current;

CREATE INDEX ix_case_summary_case_id ON case_summary (case_id);
CREATE INDEX ix_case_summary_created_by ON case_summary (created_by);

-- -----------------------------------------------------------------------------
-- 3. Case card filling
-- -----------------------------------------------------------------------------

CREATE TABLE case_card_fill_task (
    fill_task_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    fill_mode           varchar(30) NOT NULL,
    fill_status         varchar(30) NOT NULL DEFAULT 'PENDING',
    operator_id         bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at        timestamptz,
    confirmed_by        bigint REFERENCES app_user(user_id) ON DELETE SET NULL,

    CONSTRAINT ck_case_card_fill_task_mode
        CHECK (fill_mode IN ('AUTO', 'MANUAL', 'HYBRID')),
    CONSTRAINT ck_case_card_fill_task_status
        CHECK (fill_status IN ('PENDING', 'PROCESSING', 'DRAFT', 'CONFIRMED', 'FAILED')),
    CONSTRAINT ck_case_card_fill_task_confirmed
        CHECK ((confirmed_by IS NULL) = (confirmed_at IS NULL)),
    CONSTRAINT ck_case_card_fill_task_confirmed_status
        CHECK (fill_status <> 'CONFIRMED' OR confirmed_at IS NOT NULL)
);

CREATE INDEX ix_case_card_fill_task_case_id ON case_card_fill_task (case_id);
CREATE INDEX ix_case_card_fill_task_operator_id ON case_card_fill_task (operator_id);
CREATE INDEX ix_case_card_fill_task_status ON case_card_fill_task (fill_status);

-- A source row must point to exactly one typed source. This avoids an
-- untyped source_result_id that cannot be protected by a foreign key.
CREATE TABLE case_card_task_source (
    source_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fill_task_id        bigint NOT NULL REFERENCES case_card_fill_task(fill_task_id) ON DELETE CASCADE,
    doc_id              bigint REFERENCES document_parse_result(doc_id) ON DELETE RESTRICT,
    entity_result_id    bigint REFERENCES entity_result(entity_result_id) ON DELETE RESTRICT,
    element_result_id   bigint REFERENCES legal_element_result(element_result_id) ON DELETE RESTRICT,
    summary_id          bigint REFERENCES case_summary(summary_id) ON DELETE RESTRICT,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_case_card_task_source_exactly_one
        CHECK (num_nonnulls(doc_id, entity_result_id, element_result_id, summary_id) = 1)
);

CREATE INDEX ix_case_card_task_source_fill_task_id
    ON case_card_task_source (fill_task_id);
CREATE UNIQUE INDEX ux_case_card_task_source_doc
    ON case_card_task_source (fill_task_id, doc_id) WHERE doc_id IS NOT NULL;
CREATE UNIQUE INDEX ux_case_card_task_source_entity
    ON case_card_task_source (fill_task_id, entity_result_id) WHERE entity_result_id IS NOT NULL;
CREATE UNIQUE INDEX ux_case_card_task_source_element
    ON case_card_task_source (fill_task_id, element_result_id) WHERE element_result_id IS NOT NULL;
CREATE UNIQUE INDEX ux_case_card_task_source_summary
    ON case_card_task_source (fill_task_id, summary_id) WHERE summary_id IS NOT NULL;

CREATE TABLE case_card_field (
    field_id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fill_task_id            bigint NOT NULL REFERENCES case_card_fill_task(fill_task_id) ON DELETE CASCADE,
    field_code              varchar(100) NOT NULL,
    field_name              varchar(255) NOT NULL,
    field_value             text,
    field_value_json        jsonb,
    source_text             text,
    source_file_id          bigint REFERENCES evidence_file(dossier_id) ON DELETE RESTRICT,
    source_location_json    jsonb,
    confidence              numeric(5,4),
    confirm_status          varchar(30) NOT NULL DEFAULT 'UNCONFIRMED',
    confirmed_by            bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    confirmed_at            timestamptz,

    CONSTRAINT ux_case_card_field_code
        UNIQUE (fill_task_id, field_code),
    CONSTRAINT ck_case_card_field_code_not_blank
        CHECK (btrim(field_code) <> ''),
    CONSTRAINT ck_case_card_field_name_not_blank
        CHECK (btrim(field_name) <> ''),
    CONSTRAINT ck_case_card_field_value
        CHECK (field_value IS NOT NULL OR field_value_json IS NOT NULL),
    CONSTRAINT ck_case_card_field_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_case_card_field_confirm_status
        CHECK (confirm_status IN ('UNCONFIRMED', 'CONFIRMED', 'REJECTED')),
    CONSTRAINT ck_case_card_field_confirmed
        CHECK ((confirmed_by IS NULL) = (confirmed_at IS NULL)),
    CONSTRAINT ck_case_card_field_confirmed_status
        CHECK (confirm_status <> 'CONFIRMED' OR confirmed_at IS NOT NULL)
);

CREATE INDEX ix_case_card_field_fill_task_id ON case_card_field (fill_task_id);
CREATE INDEX ix_case_card_field_source_file_id ON case_card_field (source_file_id);
CREATE INDEX ix_case_card_field_confirm_status ON case_card_field (confirm_status);

-- -----------------------------------------------------------------------------
-- 4. Reports
-- -----------------------------------------------------------------------------

CREATE TABLE report_template (
    template_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name           varchar(255) NOT NULL,
    template_type           varchar(50) NOT NULL,
    template_content_json   jsonb NOT NULL,
    version_no              integer NOT NULL,
    status                  varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by              bigint NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ux_report_template_version
        UNIQUE (template_name, template_type, version_no),
    CONSTRAINT ck_report_template_name_not_blank
        CHECK (btrim(template_name) <> ''),
    CONSTRAINT ck_report_template_version
        CHECK (version_no > 0),
    CONSTRAINT ck_report_template_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'DISABLED'))
);

CREATE INDEX ix_report_template_created_by ON report_template (created_by);
CREATE INDEX ix_report_template_type_status ON report_template (template_type, status);

CREATE TABLE case_report (
    report_id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                 bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    template_id             bigint REFERENCES report_template(template_id) ON DELETE SET NULL,
    card_fill_task_id       bigint REFERENCES case_card_fill_task(fill_task_id) ON DELETE SET NULL,
    version_no              integer NOT NULL,
    report_type             varchar(50) NOT NULL,
    generate_mode           varchar(30) NOT NULL,
    operator_id             bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    report_status           varchar(30) NOT NULL DEFAULT 'GENERATING',
    report_title            varchar(255) NOT NULL,
    report_content_json     jsonb,
    error_message           text,
    generated_at            timestamptz,
    updated_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at            timestamptz,
    finalized_by            bigint REFERENCES app_user(user_id) ON DELETE SET NULL,

    CONSTRAINT ux_case_report_version
        UNIQUE (case_id, report_type, version_no),
    CONSTRAINT ck_case_report_version
        CHECK (version_no > 0),
    CONSTRAINT ck_case_report_mode
        CHECK (generate_mode IN ('AUTO', 'MANUAL', 'HYBRID')),
    CONSTRAINT ck_case_report_status
        CHECK (report_status IN ('GENERATING', 'DRAFT', 'REVIEWING', 'FINAL', 'FAILED')),
    CONSTRAINT ck_case_report_title_not_blank
        CHECK (btrim(report_title) <> ''),
    CONSTRAINT ck_case_report_failed_error
        CHECK (report_status <> 'FAILED' OR error_message IS NOT NULL),
    CONSTRAINT ck_case_report_finalized
        CHECK ((finalized_by IS NULL) = (finalized_at IS NULL)),
    CONSTRAINT ck_case_report_final_status
        CHECK (report_status <> 'FINAL' OR finalized_at IS NOT NULL)
);

CREATE INDEX ix_case_report_case_id ON case_report (case_id);
CREATE INDEX ix_case_report_template_id ON case_report (template_id);
CREATE INDEX ix_case_report_card_fill_task_id ON case_report (card_fill_task_id);
CREATE INDEX ix_case_report_operator_id ON case_report (operator_id);
CREATE INDEX ix_case_report_status ON case_report (report_status);

CREATE TRIGGER trg_case_report_updated_at
BEFORE UPDATE ON case_report
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE report_evidence (
    report_id           bigint NOT NULL REFERENCES case_report(report_id) ON DELETE CASCADE,
    dossier_id          bigint NOT NULL REFERENCES evidence_file(dossier_id) ON DELETE RESTRICT,
    sort_no             integer,

    PRIMARY KEY (report_id, dossier_id),
    CONSTRAINT ck_report_evidence_sort_no
        CHECK (sort_no IS NULL OR sort_no > 0)
);

CREATE INDEX ix_report_evidence_dossier_id ON report_evidence (dossier_id);

CREATE TABLE report_legal_element_result (
    report_id           bigint NOT NULL REFERENCES case_report(report_id) ON DELETE CASCADE,
    element_result_id   bigint NOT NULL REFERENCES legal_element_result(element_result_id) ON DELETE RESTRICT,

    PRIMARY KEY (report_id, element_result_id)
);

CREATE INDEX ix_report_legal_element_result_element_id
    ON report_legal_element_result (element_result_id);

-- -----------------------------------------------------------------------------
-- 5. Typical cases and recommendations
-- -----------------------------------------------------------------------------

CREATE TABLE typical_case (
    typical_case_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_case_id        varchar(100),
    title                   varchar(255) NOT NULL,
    case_cause              varchar(255),
    case_cause_full_json    jsonb,
    case_type               varchar(50),
    country                 varchar(100),
    court                   varchar(255),
    court_level             varchar(50),
    doc_type                varchar(50),
    dispute_focus_json      jsonb,
    judgment_date           date,
    procedure               varchar(100),
    applicable_law_json     jsonb,
    case_level              varchar(50),
    embedding               public.vector,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_typical_case_title_not_blank
        CHECK (btrim(title) <> '')
);

CREATE UNIQUE INDEX ux_typical_case_external_case_id
    ON typical_case (external_case_id)
    WHERE external_case_id IS NOT NULL;

CREATE INDEX ix_typical_case_case_cause ON typical_case (case_cause);
CREATE INDEX ix_typical_case_judgment_date ON typical_case (judgment_date);

CREATE TRIGGER trg_typical_case_updated_at
BEFORE UPDATE ON typical_case
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE typical_case_content (
    typical_case_id     bigint PRIMARY KEY REFERENCES typical_case(typical_case_id) ON DELETE CASCADE,
    content             text,
    fact                text,

    CONSTRAINT ck_typical_case_content_present
        CHECK (content IS NOT NULL OR fact IS NOT NULL)
);

CREATE TABLE case_recommendation (
    recommend_id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                     bigint NOT NULL REFERENCES case_record(case_id) ON DELETE RESTRICT,
    source_summary_id           bigint REFERENCES case_summary(summary_id) ON DELETE SET NULL,
    query_fact_text             text,
    query_fact_embedding        public.vector,
    query_dispute_focus_json    jsonb,
    model_name                  varchar(100),
    model_version               varchar(100),
    created_by                  bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at                  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_case_recommendation_query_present
        CHECK (query_fact_text IS NOT NULL OR query_fact_embedding IS NOT NULL OR query_dispute_focus_json IS NOT NULL)
);

CREATE INDEX ix_case_recommendation_case_id ON case_recommendation (case_id);
CREATE INDEX ix_case_recommendation_source_summary_id ON case_recommendation (source_summary_id);
CREATE INDEX ix_case_recommendation_created_by ON case_recommendation (created_by);

CREATE TABLE case_recommendation_item (
    item_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommend_id         bigint NOT NULL REFERENCES case_recommendation(recommend_id) ON DELETE CASCADE,
    typical_case_id      bigint NOT NULL REFERENCES typical_case(typical_case_id) ON DELETE RESTRICT,
    rank_no              integer NOT NULL,
    similarity_score     numeric(8,6),
    reason_json          jsonb,

    CONSTRAINT ux_case_recommendation_item_rank
        UNIQUE (recommend_id, rank_no),
    CONSTRAINT ux_case_recommendation_item_case
        UNIQUE (recommend_id, typical_case_id),
    CONSTRAINT ck_case_recommendation_item_rank
        CHECK (rank_no > 0),
    CONSTRAINT ck_case_recommendation_item_score
        CHECK (similarity_score IS NULL OR (similarity_score >= -1 AND similarity_score <= 1))
);

CREATE INDEX ix_case_recommendation_item_typical_case_id
    ON case_recommendation_item (typical_case_id);

-- Vector indexes are intentionally omitted because the embedding dimension and
-- distance operator depend on the selected model. After fixing a dimension,
-- change both vector columns to vector(<dimension>) and create HNSW indexes.

-- -----------------------------------------------------------------------------
-- 6. Audit log
-- -----------------------------------------------------------------------------

CREATE TABLE operation_log (
    log_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    case_id             bigint REFERENCES case_record(case_id) ON DELETE SET NULL,
    operation_type      varchar(50) NOT NULL,
    object_type         varchar(50),
    object_id           varchar(100),
    operation_result    varchar(30) NOT NULL,
    operation_time      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    detail              jsonb,
    request_id          varchar(100),

    CONSTRAINT ck_operation_log_type_not_blank
        CHECK (btrim(operation_type) <> ''),
    CONSTRAINT ck_operation_log_result
        CHECK (operation_result IN ('SUCCESS', 'FAILED'))
);

CREATE INDEX ix_operation_log_user_time
    ON operation_log (user_id, operation_time DESC);
CREATE INDEX ix_operation_log_case_time
    ON operation_log (case_id, operation_time DESC);
CREATE INDEX ix_operation_log_request_id
    ON operation_log (request_id)
    WHERE request_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 7. Documentation comments
-- -----------------------------------------------------------------------------

COMMENT ON SCHEMA lexpro IS 'LexPro application schema';
COMMENT ON TABLE app_user IS 'Application user and authorization subject';
COMMENT ON TABLE case_record IS 'Case master record';
COMMENT ON TABLE case_party IS 'People and organizations participating in a case';
COMMENT ON TABLE case_assignment IS 'Case staff assignment history';
COMMENT ON TABLE evidence_file IS 'Electronic dossier file metadata';
COMMENT ON TABLE document_parse_result IS 'Versioned document parsing output';
COMMENT ON TABLE entity_result IS 'Entity extraction output for a parsed document';
COMMENT ON TABLE legal_element_result IS 'Legal element extraction and confirmation output';
COMMENT ON TABLE case_summary IS 'Versioned case summary by summary type';
COMMENT ON TABLE case_card_fill_task IS 'Case card filling task';
COMMENT ON TABLE case_card_task_source IS 'Typed source records used by a case card filling task';
COMMENT ON TABLE case_card_field IS 'Generated or manually filled case card field';
COMMENT ON TABLE report_template IS 'Versioned report template';
COMMENT ON TABLE case_report IS 'Versioned case review report';
COMMENT ON TABLE report_evidence IS 'Evidence files referenced by a report';
COMMENT ON TABLE report_legal_element_result IS 'Legal element outputs referenced by a report';
COMMENT ON TABLE typical_case IS 'Typical case metadata and embedding';
COMMENT ON TABLE typical_case_content IS 'Full text and fact section of a typical case';
COMMENT ON TABLE case_recommendation IS 'Recommendation query snapshot for a case';
COMMENT ON TABLE case_recommendation_item IS 'Ranked typical cases returned by a recommendation';
COMMENT ON TABLE operation_log IS 'Append-only operation audit log';

COMMENT ON COLUMN evidence_file.file_url IS
    'Store an object-storage key or internal URI, not a permanent public URL';
COMMENT ON COLUMN typical_case.embedding IS
    'Dimensionless pgvector until the embedding model and vector dimension are fixed';
COMMENT ON COLUMN case_recommendation.query_fact_embedding IS
    'Must have the same dimension as typical_case.embedding';
