-- Apply only after approval and a verified database backup. V1-V6 stay unchanged.
CREATE TABLE lexpro.model_api_configuration (
    config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name varchar(100) NOT NULL,
    model_name varchar(100) NOT NULL,
    base_url varchar(2048) NOT NULL,
    api_key_ciphertext text NOT NULL,
    enable_thinking boolean NOT NULL DEFAULT false,
    remark varchar(500) NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    active boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_model_config_names CHECK (btrim(display_name) <> '' AND btrim(model_name) <> ''),
    CONSTRAINT ck_model_config_active CHECK (NOT active OR enabled)
);
CREATE UNIQUE INDEX ux_model_config_single_active ON lexpro.model_api_configuration ((active)) WHERE active;
CREATE TRIGGER trg_model_configuration_updated_at BEFORE UPDATE ON lexpro.model_api_configuration
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();
