-- LexPro schema upgrade V3: lean normalized workspace model
-- Prerequisite: lexpro_schema_upgrade_v2_core.sql
-- This migration adds six tables:
--   organization_unit, auth_role, auth_permission, auth_role_permission,
--   knowledge_content, work_task
-- Run once:
--   psql -v ON_ERROR_STOP=1 -d lexpro -f DBM/lexpro_schema_upgrade_v3_workspace.sql

BEGIN;

SET LOCAL search_path TO lexpro, public;

DO $$
BEGIN
    IF to_regclass('lexpro.dossier_folder') IS NULL
       OR NOT EXISTS (
           SELECT 1
           FROM information_schema.columns
           WHERE table_schema = 'lexpro'
             AND table_name = 'case_report'
             AND column_name = 'is_current'
       ) THEN
        RAISE EXCEPTION 'LexPro V2 migration is not installed';
    END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- 1. Organization and single-role RBAC
--
-- Current requirements give each user one primary department and one system
-- role. A membership table and a user-role join table would be unnecessary.
-- -----------------------------------------------------------------------------

CREATE TABLE organization_unit (
    organization_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_organization_id bigint REFERENCES organization_unit(organization_id) ON DELETE RESTRICT,
    organization_code      varchar(100) NOT NULL,
    organization_name      varchar(255) NOT NULL,
    organization_type      varchar(30) NOT NULL DEFAULT 'DEPARTMENT',
    leader_user_id         bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    description            text,
    sort_no                integer,
    status                 varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_organization_code_not_blank CHECK (btrim(organization_code) <> ''),
    CONSTRAINT ck_organization_name_not_blank CHECK (btrim(organization_name) <> ''),
    CONSTRAINT ck_organization_type
        CHECK (organization_type IN ('ROOT', 'DEPARTMENT', 'TEAM')),
    CONSTRAINT ck_organization_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_organization_sort CHECK (sort_no IS NULL OR sort_no >= 0),
    CONSTRAINT ck_organization_not_self
        CHECK (parent_organization_id IS NULL OR parent_organization_id <> organization_id)
);

CREATE UNIQUE INDEX ux_organization_code_lower
    ON organization_unit (lower(organization_code));
CREATE INDEX ix_organization_parent ON organization_unit (parent_organization_id);

CREATE TRIGGER trg_organization_updated_at
BEFORE UPDATE ON organization_unit
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE auth_role (
    role_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code           varchar(100) NOT NULL UNIQUE,
    role_name           varchar(255) NOT NULL,
    description         text,
    is_system           boolean NOT NULL DEFAULT false,
    status              varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_auth_role_code_not_blank CHECK (btrim(role_code) <> ''),
    CONSTRAINT ck_auth_role_name_not_blank CHECK (btrim(role_name) <> ''),
    CONSTRAINT ck_auth_role_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TRIGGER trg_auth_role_updated_at
BEFORE UPDATE ON auth_role
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

CREATE TABLE auth_permission (
    permission_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code     varchar(150) NOT NULL UNIQUE,
    permission_name     varchar(255) NOT NULL,
    description         text,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_auth_permission_code_not_blank CHECK (btrim(permission_code) <> ''),
    CONSTRAINT ck_auth_permission_name_not_blank CHECK (btrim(permission_name) <> '')
);

CREATE TABLE auth_role_permission (
    role_id             bigint NOT NULL REFERENCES auth_role(role_id) ON DELETE CASCADE,
    permission_id       bigint NOT NULL REFERENCES auth_permission(permission_id) ON DELETE CASCADE,

    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX ix_auth_role_permission_permission
    ON auth_role_permission (permission_id);

INSERT INTO auth_role (role_code, role_name, is_system)
VALUES
    ('ADMIN', 'System administrator', true),
    ('USER', 'Standard user', true);

INSERT INTO auth_permission (permission_code, permission_name)
VALUES
    ('DASHBOARD_VIEW', 'View dashboard'),
    ('CASE_READ', 'Read assigned cases'),
    ('CASE_WRITE', 'Edit assigned cases'),
    ('CASE_ASSIGN', 'Assign case staff'),
    ('DOSSIER_MANAGE', 'Manage dossier files'),
    ('AI_EXECUTE', 'Run intelligent processing'),
    ('REPORT_MANAGE', 'Generate and edit reports'),
    ('RECOMMENDATION_USE', 'Use case recommendations'),
    ('TASK_MANAGE', 'Manage work tasks'),
    ('USER_MANAGE', 'Manage users and organizations'),
    ('CONTENT_MANAGE', 'Manage knowledge content');

INSERT INTO auth_role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM auth_role r
CROSS JOIN auth_permission p
WHERE r.role_code = 'ADMIN';

INSERT INTO auth_role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM auth_role r
JOIN auth_permission p
  ON p.permission_code IN (
      'DASHBOARD_VIEW',
      'CASE_READ',
      'CASE_WRITE',
      'DOSSIER_MANAGE',
      'AI_EXECUTE',
      'REPORT_MANAGE',
      'RECOMMENDATION_USE',
      'TASK_MANAGE'
  )
WHERE r.role_code = 'USER';

ALTER TABLE app_user
    ADD COLUMN organization_id bigint REFERENCES organization_unit(organization_id) ON DELETE SET NULL,
    ADD COLUMN role_id bigint REFERENCES auth_role(role_id) ON DELETE RESTRICT;

UPDATE app_user u
SET role_id = r.role_id
FROM auth_role r
WHERE r.role_code = u.role;

ALTER TABLE app_user
    ALTER COLUMN role_id SET NOT NULL;

-- Unknown JSON authorization cannot be normalized safely. Abort instead of
-- silently dropping real permissions or scopes.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM app_user
        WHERE permissions_json <> '{}'::jsonb
           OR case_scope <> '{}'::jsonb
    ) THEN
        RAISE EXCEPTION
            'Non-empty legacy permissions_json/case_scope found; migrate them before V3';
    END IF;
END;
$$;

ALTER TABLE app_user
    DROP COLUMN role,
    DROP COLUMN permissions_json,
    DROP COLUMN case_scope;

CREATE INDEX ix_app_user_organization ON app_user (organization_id);
CREATE INDEX ix_app_user_role ON app_user (role_id);

-- -----------------------------------------------------------------------------
-- 2. Remove duplicated legacy case/person attributes
-- -----------------------------------------------------------------------------

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM case_party
        WHERE age IS NOT NULL AND birth_date IS NULL
    ) THEN
        RAISE EXCEPTION
            'Legacy case_party.age data exists without birth_date; migrate it before V3';
    END IF;
END;
$$;

DROP INDEX ix_case_record_prosecutor_id;
DROP INDEX ix_evidence_file_case_parse_status;
DROP INDEX ux_case_assignment_current;
DROP INDEX ix_case_assignment_current_case_role;

ALTER TABLE case_record
    DROP CONSTRAINT ck_case_record_dates,
    DROP COLUMN prosecutor_id,
    DROP COLUMN deadline_date;

ALTER TABLE case_party
    DROP COLUMN age;

ALTER TABLE evidence_file
    DROP COLUMN parse_status;

-- case_assignment also represents explicit case sharing; no separate ACL table.
ALTER TABLE case_assignment
    DROP CONSTRAINT ck_case_assignment_role,
    DROP CONSTRAINT ck_case_assignment_current_end,
    DROP COLUMN is_current,
    ADD COLUMN access_level varchar(20) NOT NULL DEFAULT 'EDIT',
    ADD CONSTRAINT ck_case_assignment_role
        CHECK (assignment_role IN ('PROSECUTOR', 'ASSIGNEE', 'REVIEWER', 'COLLABORATOR')),
    ADD CONSTRAINT ck_case_assignment_access
        CHECK (access_level IN ('VIEW', 'EDIT', 'MANAGE'));

CREATE UNIQUE INDEX ux_case_assignment_current
    ON case_assignment (case_id, user_id, assignment_role)
    WHERE ended_at IS NULL;

CREATE INDEX ix_case_assignment_current_case_role
    ON case_assignment (case_id, assignment_role)
    WHERE ended_at IS NULL;

-- -----------------------------------------------------------------------------
-- 3. Minimal content management
--
-- Report templates and typical cases keep their dedicated tables. This table
-- only stores general knowledge, rules and checklists.
-- -----------------------------------------------------------------------------

CREATE TABLE knowledge_content (
    content_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type         varchar(30) NOT NULL,
    title                varchar(255) NOT NULL,
    content_text         text,
    content_json         jsonb,
    owner_organization_id bigint REFERENCES organization_unit(organization_id) ON DELETE SET NULL,
    status               varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by           bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    reviewed_by          bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    reviewed_at          timestamptz,
    published_by         bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    published_at         timestamptz,
    created_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_knowledge_content_type
        CHECK (content_type IN ('KNOWLEDGE', 'RULE', 'CHECKLIST')),
    CONSTRAINT ck_knowledge_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_knowledge_body
        CHECK (content_text IS NOT NULL OR content_json IS NOT NULL),
    CONSTRAINT ck_knowledge_json
        CHECK (content_json IS NULL OR jsonb_typeof(content_json) IN ('object', 'array')),
    CONSTRAINT ck_knowledge_status
        CHECK (status IN ('DRAFT', 'REVIEWING', 'PUBLISHED', 'REJECTED', 'ARCHIVED')),
    CONSTRAINT ck_knowledge_review_actor
        CHECK (reviewed_by IS NULL OR reviewed_at IS NOT NULL),
    CONSTRAINT ck_knowledge_publish_actor
        CHECK (published_by IS NULL OR published_at IS NOT NULL),
    CONSTRAINT ck_knowledge_published
        CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
);

CREATE INDEX ix_knowledge_content_type_status
    ON knowledge_content (content_type, status);
CREATE INDEX ix_knowledge_content_updated
    ON knowledge_content (updated_at DESC);

CREATE TRIGGER trg_knowledge_content_updated_at
BEFORE UPDATE ON knowledge_content
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

-- -----------------------------------------------------------------------------
-- 4. Human work tasks
--
-- Technical processing state remains in parse/result/report tables. Task event
-- history is written to the existing operation_log with object_type='WORK_TASK'.
-- -----------------------------------------------------------------------------

CREATE TABLE work_task (
    task_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id              bigint REFERENCES case_record(case_id) ON DELETE CASCADE,
    content_id           bigint REFERENCES knowledge_content(content_id) ON DELETE CASCADE,
    task_type            varchar(50) NOT NULL,
    title                varchar(255) NOT NULL,
    description          text,
    task_status          varchar(30) NOT NULL DEFAULT 'PENDING',
    priority             varchar(20) NOT NULL DEFAULT 'MEDIUM',
    assignee_id          bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_by           bigint REFERENCES app_user(user_id) ON DELETE SET NULL,
    due_at               timestamptz,
    closed_at            timestamptz,
    created_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_work_task_subject
        CHECK (num_nonnulls(case_id, content_id) = 1),
    CONSTRAINT ck_work_task_type_not_blank CHECK (btrim(task_type) <> ''),
    CONSTRAINT ck_work_task_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_work_task_status
        CHECK (task_status IN (
            'PENDING', 'PROCESSING', 'WAITING_CONFIRMATION', 'COMPLETED', 'CANCELLED'
        )),
    CONSTRAINT ck_work_task_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT ck_work_task_closed
        CHECK ((task_status IN ('COMPLETED', 'CANCELLED')) = (closed_at IS NOT NULL)),
    CONSTRAINT ck_work_task_due
        CHECK (due_at IS NULL OR due_at >= created_at)
);

CREATE INDEX ix_work_task_assignee_status_due
    ON work_task (assignee_id, task_status, due_at);
CREATE INDEX ix_work_task_case_status
    ON work_task (case_id, task_status)
    WHERE case_id IS NOT NULL;
CREATE INDEX ix_work_task_overdue
    ON work_task (due_at)
    WHERE task_status NOT IN ('COMPLETED', 'CANCELLED') AND due_at IS NOT NULL;

CREATE TRIGGER trg_work_task_updated_at
BEFORE UPDATE ON work_task
FOR EACH ROW EXECUTE FUNCTION lexpro.set_updated_at();

COMMENT ON TABLE organization_unit IS 'Single primary organization hierarchy for users.';
COMMENT ON TABLE auth_role IS 'Single system role assigned by app_user.role_id.';
COMMENT ON TABLE auth_permission IS 'Atomic backend permissions.';
COMMENT ON TABLE auth_role_permission IS 'Role-to-permission many-to-many relation.';
COMMENT ON TABLE knowledge_content IS 'General knowledge, rules and checklists.';
COMMENT ON TABLE work_task IS 'Human-facing work items; event history uses operation_log.';

COMMIT;
