<template>
  <div v-loading="loading">
    <div class="toolbar"><span class="muted">账号、角色与功能权限管理(权限由角色统一配置)</span><button class="btn primary" style="margin-left:auto" type="button" @click="openCreate">+ 新增用户</button></div>
    <div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>账号</th><th>姓名</th><th>角色</th><th>数据范围</th><th>状态</th><th>权限</th><th>创建时间</th><th>操作</th></tr></thead><tbody>
      <tr v-if="!users.length"><td colspan="9" class="empty">暂无用户</td></tr>
      <tr v-for="row in users" :key="row.userId"><td>{{ row.userId }}</td><td><b>{{ row.username }}</b><span v-if="row.userId === currentUser?.userId" class="badge b-blue" style="margin-left:5px">当前</span></td><td>{{ row.realName || '-' }}</td><td><span class="tag" :class="roleClass(row.roleId)">{{ roleName(row.roleId) }}</span></td><td>{{ roleScope(row.roleId) }}</td><td><span class="badge" :class="row.status === 'ACTIVE' ? 'b-green' : 'b-red'">{{ row.status === 'ACTIVE' ? '启用' : '停用' }}</span></td><td class="muted permission-cell">{{ permissionSummary(row.roleId) }}</td><td>{{ formatDate(row.createdAt) }}</td><td><button class="btn ghost sm" type="button" @click="openEdit(row)">编辑</button> <button class="btn ghost sm" :class="{danger:row.status==='ACTIVE'}" :disabled="saving||row.userId===currentUser?.userId" @click="toggleStatus(row)">{{ row.status==='ACTIVE'?'禁用':'启用' }}</button></td></tr>
    </tbody></table></div></div>
    <div v-if="modalVisible" class="overlay" @click.self="closeModal"><div class="modal"><div class="modal-header"><h3>{{ editing ? '编辑用户' : '新增用户' }}</h3><button class="close-x" type="button" @click="closeModal">×</button></div><div class="modal-body">
      <div class="g2 grid"><div class="field"><label>账号 *</label><input v-model.trim="form.username" :disabled="editing"></div><div class="field"><label>姓名 *</label><input v-model.trim="form.realName" :disabled="editing"></div><div class="field"><label>{{ editing ? '重置密码(留空不改)' : '初始密码 *' }}</label><input v-model="form.password" type="password" autocomplete="new-password"></div><div class="field"><label>角色</label><select v-model="form.roleId" :disabled="editing"><option v-for="r in roles" :key="r.roleId" :value="r.roleId">{{ r.name }}</option></select></div><div class="field"><label>案件数据范围</label><select disabled><option>{{ roleScope(form.roleId) }}</option></select></div><div class="field"><label>状态</label><select v-model="form.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><div v-if="!editing" class="field"><label>所属组织</label><select v-model="form.organizationId"><option v-for="org in flatOrganizations" :key="org.organizationId" :value="org.organizationId">{{ org.name }}</option></select></div></div>
      <div class="field mt8"><label>功能权限(跟随角色)</label><div class="perm-box"><div class="perm-group"><div class="pg-items"><label v-for="permission in selectedPermissions" :key="permission" class="perm-check"><input type="checkbox" checked disabled> {{ permissionLabel(permission) }}</label></div></div></div></div>
    </div><div class="modal-footer"><button class="btn ghost" type="button" @click="closeModal">取消</button><button class="btn primary" type="button" :disabled="saving" @click="save">保存</button></div></div></div>
  </div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue'
import { ElMessage } from 'element-plus'
import { createUser,listOrganizations,listRoles,listUsers,resetUserPassword,updateUserStatus } from '../api/admin'
import { currentUser } from '../auth/session'
const labels={DASHBOARD_VIEW:'工作台',CASE_READ:'案件查看',CASE_WRITE:'案件编辑',CASE_ASSIGN:'案件分配',DOSSIER_MANAGE:'卷宗上传与管理',AI_EXECUTE:'实体、要素与摘要分析',REPORT_MANAGE:'审查报告',RECOMMENDATION_USE:'类案推送',TASK_MANAGE:'任务管理',USER_MANAGE:'用户与日志管理',CONTENT_MANAGE:'知识内容管理'}
const organizations=ref([]),users=ref([]),roles=ref([]),loading=ref(false),saving=ref(false),modalVisible=ref(false),editing=ref(false),selectedUser=ref(null),form=ref({username:'',realName:'',password:'',organizationId:null,roleId:null,status:'ACTIVE'})
const flatOrganizations=computed(()=>flatten(organizations.value)),selectedPermissions=computed(()=>roles.value.find(r=>r.roleId===form.value.roleId)?.permissions||[])
onMounted(load)
async function toggleStatus(row){saving.value=true;try{await updateUserStatus(row.userId,row.status==='ACTIVE'?'DISABLED':'ACTIVE');ElMessage.success(row.status==='ACTIVE'?'用户已禁用':'用户已启用');await load()}catch(error){ElMessage.error(error.message)}finally{saving.value=false}}
async function load(){loading.value=true;try{const [orgs,page,roleList]=await Promise.all([listOrganizations(),listUsers(),listRoles()]);organizations.value=orgs;users.value=page.items||[];roles.value=roleList||[]}catch(error){ElMessage.error(error.message)}finally{loading.value=false}}
function flatten(items,depth=0){return items.flatMap(item=>[{...item,depth},...flatten(item.children||[],depth+1)])}function role(id){return roles.value.find(item=>item.roleId===id)}function roleName(id){return role(id)?.name||'-'}function roleScope(){return '本人承办或已授权案件'}function roleClass(id){const name=roleName(id);return name==='管理员'?'gold':name==='检察官'?'green':'blue'}function permissionLabel(code){return labels[code]||code}function permissionSummary(id){const p=role(id)?.permissions||[];return p.includes('*')?'全部权限':p.length?p.map(permissionLabel).join('、'):'角色默认'}function formatDate(value){return value?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'}
function openCreate(){editing.value=false;selectedUser.value=null;form.value={username:'',realName:'',password:'',organizationId:flatOrganizations.value[0]?.organizationId||null,roleId:roles.value[0]?.roleId||null,status:'ACTIVE'};modalVisible.value=true}function openEdit(row){editing.value=true;selectedUser.value=row;form.value={username:row.username,realName:row.realName,password:'',organizationId:row.organizationId,roleId:row.roleId,status:row.status};modalVisible.value=true}function closeModal(){modalVisible.value=false}
async function save(){saving.value=true;try{if(editing.value){if(form.value.status!==selectedUser.value.status)await updateUserStatus(selectedUser.value.userId,form.value.status);if(form.value.password)await resetUserPassword(selectedUser.value.userId,form.value.password);ElMessage.success('用户已更新')}else{await createUser({username:form.value.username,realName:form.value.realName,password:form.value.password,organizationId:form.value.organizationId,roleId:form.value.roleId});ElMessage.success('用户创建成功')}closeModal();await load()}catch(error){ElMessage.error(error.message)}finally{saving.value=false}}
</script>
<style scoped>.permission-cell{max-width:220px;font-size:12px;white-space:normal}.perm-group{padding:8px 0}.pg-items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.perm-check{color:var(--text)!important;margin:0!important}.modal input:disabled,.modal select:disabled{background:#f5f7fa;color:#8b96a5}</style>
