<template>
  <LegalFeatureContext title="审查报告" @case="loadReports">
    <div class="card mt16"><div class="card-title"><span class="bar"></span>审查报告列表<span class="muted-sm" style="margin-left:8px">共 {{ reports.length }} 份,同一案件可多次生成</span><button v-if="canGenerate" class="btn primary sm" style="margin-left:auto" @click="openGenerator">生成报告初稿</button></div><div class="card-pad"><div class="table-wrap"><table class="table"><thead><tr><th>编号</th><th>标题</th><th>类型</th><th>状态</th><th>生成时间</th><th>操作</th></tr></thead><tbody><tr v-if="!reports.length"><td colspan="6" class="empty">尚未生成审查报告,点击右上角“生成报告初稿”开始</td></tr><tr v-for="row in reports" :key="row.reportId"><td class="mono" style="font-size:12px">{{ row.reportNo || `R-${row.reportId}` }}</td><td style="max-width:260px">{{ row.reportTitle }}</td><td>{{ row.reportType }}</td><td><span class="badge" :class="statusClass(row.reportStatus)">{{ statusLabel(row.reportStatus) }}</span></td><td>{{ formatTime(row.createdAt || row.updatedAt) }}</td><td><button class="btn ghost sm" @click="openReport(row)">查看/编辑</button> <button class="btn ghost sm" @click="openReport(row).then(()=>download('DOCX'))">导出/预览</button></td></tr></tbody></table></div></div></div>

    <div v-if="detail" class="mt16"><div class="cause-banner"><b>{{ detail.report.reportTitle }}</b><span>版本 V{{ detail.report.versionNo }}</span><span class="badge" :class="statusClass(detail.report.reportStatus)">{{ statusLabel(detail.report.reportStatus) }}</span><span v-if="!detail.report.current" class="muted">历史版本只读</span><div class="flex" style="margin-left:auto"><button class="btn ghost sm" @click="download('DOCX')">导出 DOCX</button><button class="btn ghost sm" @click="download('PDF')">导出 PDF</button></div></div><div class="card"><div class="card-pad report-editor"><div v-for="section in draftContent.sections||[]" :key="section.code" class="field"><label><b>{{ section.title }}</b></label><textarea v-if="editing" v-model="section.content" rows="7"></textarea><div v-else class="report-text">{{ section.content }}</div></div><div class="flex flex-end"><button v-if="detail.report.current&&detail.report.reportStatus==='DRAFT'" class="btn ghost" @click="editing=!editing">{{ editing?'取消编辑':'编辑草稿' }}</button><button v-if="editing" class="btn primary" :disabled="saving" @click="saveDraft">{{ saving?'保存中…':'保存草稿' }}</button><button v-if="detail.report.current&&detail.report.reportStatus==='DRAFT'&&!editing" class="btn gold" @click="submit">提交复核</button><button v-if="detail.report.current&&detail.report.reportStatus==='REVIEWING'" class="btn ghost danger" @click="returnVisible=true">退回</button><button v-if="detail.report.current&&detail.report.reportStatus==='REVIEWING'" class="btn success" @click="finalize">确认定稿</button></div></div></div></div>
  </LegalFeatureContext>

  <div v-if="generatorVisible" class="overlay"><div class="modal"><div class="modal-header"><h3>生成审查报告</h3><button class="close-x" @click="generatorVisible=false">×</button></div><div class="modal-body"><div class="field"><label>报告类型</label><input v-model="generator.reportType" disabled></div><div class="field"><label>报告标题 *</label><input v-model="generator.reportTitle" maxlength="255"></div><div class="field"><label>启用模板 *</label><select v-model="generator.templateId" @change="alignReportType"><option :value="null">请选择模板</option><option v-for="item in templates" :key="item.templateId" :value="item.templateId">{{ item.templateName }}（{{ item.templateType }} · V{{ item.versionNo }}）</option></select></div><div class="field"><label>确认案卡</label><select v-model="generator.cardFillTaskId"><option :value="null">不使用案卡</option><option v-for="item in confirmedCards" :key="item.fillTaskId" :value="item.fillTaskId">案卡 #{{ item.fillTaskId }} · {{ formatTime(item.confirmedAt) }}</option></select></div><div class="field"><label>已解析卷宗来源 *</label><div class="report-sources"><label v-for="item in evidenceOptions" :key="item.dossierId"><input v-model="selectedDossierIds" type="checkbox" :value="item.dossierId"><span>{{ item.fileName }}</span><small>{{ item.textChars }} 字</small></label><div v-if="!evidenceOptions.length" class="muted-sm">当前案件暂无解析成功的卷宗，可改用已确认案卡。</div></div></div><div class="login-tip">至少选择一份卷宗或一个已确认案卡；长材料将按模型上下文安全截取。</div></div><div class="modal-footer"><button class="btn ghost" @click="generatorVisible=false">取消</button><button class="btn primary" :disabled="generating" @click="generateReport">{{ generating?'生成中…':'开始生成' }}</button></div></div></div>
  <div v-if="returnVisible" class="overlay"><div class="modal small-modal"><div class="modal-header"><h3>退回报告</h3><button class="close-x" @click="returnVisible=false">×</button></div><div class="modal-body"><div class="field"><label>退回原因</label><textarea v-model="returnReason" rows="4" placeholder="填写退回原因"></textarea></div></div><div class="modal-footer"><button class="btn ghost" @click="returnVisible=false">取消</button><button class="btn danger" @click="returnToDraft">确认退回</button></div></div></div>
</template>

<script setup>
import { computed,ref } from 'vue'
import { ElMessage } from 'element-plus'
import LegalFeatureContext from '../components/common/LegalFeatureContext.vue'
import { hasPermission } from '../auth/session'
import { exportReport,finalizeReport,getReport,getReportJob,listCaseCards,listReports,listReportTemplates,returnReport,startReport,submitReportReview,updateReportDraft } from '../api/reports'
import { getParsedDocument,listDossierFiles,listParseResults } from '../api/dossier'
import { saveBlob } from '../utils/download'
import { waitForJob } from '../utils/jobs'

const caseId=ref(null),reports=ref([]),detail=ref(null),returnVisible=ref(false),returnReason=ref(''),editing=ref(false),saving=ref(false),generatorVisible=ref(false),generating=ref(false),templates=ref([]),confirmedCards=ref([]),evidenceOptions=ref([]),selectedDossierIds=ref([])
const draftContent=computed(()=>detail.value?.content||{sections:[]}),canGenerate=hasPermission('REPORT_MANAGE')&&hasPermission('AI_EXECUTE'),generator=ref({reportType:'REVIEW_REPORT',reportTitle:'',templateId:null,cardFillTaskId:null})
async function loadReports(value){caseId.value=value;detail.value=null;if(!value)return;try{reports.value=await listReports(value);if(reports.value.length)await openReport(reports.value.find((item)=>item.current)||reports.value[0])}catch(error){ElMessage.error(error.message)}}
async function openReport(row){if(!row)return;try{detail.value=await getReport(caseId.value,row.reportId);editing.value=false;return detail.value}catch(error){ElMessage.error(error.message)}}
async function saveDraft(){saving.value=true;try{detail.value=await updateReportDraft(caseId.value,detail.value.report.reportId,{reportTitle:detail.value.report.reportTitle,content:draftContent.value,lockVersion:detail.value.report.lockVersion});editing.value=false;ElMessage.success('草稿已保存')}catch(error){ElMessage.error(error.message)}finally{saving.value=false}}
async function transition(action,message){try{detail.value=await action();ElMessage.success(message);await loadReports(caseId.value)}catch(error){ElMessage.error(error.message)}}
const submit=()=>transition(()=>submitReportReview(caseId.value,detail.value.report.reportId,detail.value.report.lockVersion),'已提交复核'),finalize=()=>transition(()=>finalizeReport(caseId.value,detail.value.report.reportId,detail.value.report.lockVersion),'报告已定稿')
async function returnToDraft(){if(!returnReason.value.trim())return ElMessage.warning('请填写退回原因');await transition(()=>returnReport(caseId.value,detail.value.report.reportId,detail.value.report.lockVersion,returnReason.value.trim()),'报告已退回草稿');returnVisible.value=false}
async function download(format){try{saveBlob(await exportReport(caseId.value,detail.value.report.reportId,format),`LexPro-report.${format.toLowerCase()}`)}catch(error){ElMessage.error(error.message)}}
async function openGenerator(){try{const values=await Promise.all([listReportTemplates('ACTIVE'),listCaseCards(caseId.value),loadEvidenceOptions(caseId.value)]);templates.value=values[0];confirmedCards.value=values[1].filter((item)=>item.fillStatus==='CONFIRMED');evidenceOptions.value=values[2];selectedDossierIds.value=values[2].length?[values[2][0].dossierId]:[];const template=templates.value[0];generator.value={reportType:template?.templateType||'',reportTitle:'审查报告',templateId:template?.templateId||null,cardFillTaskId:null};generatorVisible.value=true}catch(error){ElMessage.error(error.message)}}
async function loadEvidenceOptions(id){const files=await listDossierFiles(id);const options=await Promise.all(files.map(async(file)=>{const parses=await listParseResults(id,file.dossierId),current=parses.find(item=>item.current&&item.parseStatus==='SUCCESS')||parses.find(item=>item.parseStatus==='SUCCESS');if(!current)return null;const document=await getParsedDocument(id,current.docId);return{dossierId:file.dossierId,fileName:file.fileName,textChars:document.rawText?.length||0}}));return options.filter(Boolean).sort((a,b)=>a.textChars-b.textChars)}
function alignReportType(){const template=templates.value.find((item)=>item.templateId===generator.value.templateId);generator.value.reportType=template?.templateType||''}
async function generateReport(){const template=templates.value.find((item)=>item.templateId===generator.value.templateId);if(!template||!generator.value.reportTitle.trim())return ElMessage.warning('请填写报告标题并选择模板');if(!generator.value.cardFillTaskId&&!selectedDossierIds.value.length)return ElMessage.warning('请至少选择一份卷宗或一个已确认案卡');generating.value=true;try{const evidence=selectedDossierIds.value.map((dossierId,index)=>({dossierId,sortNo:index+1}));const created=await startReport(caseId.value,{...generator.value,reportType:template.templateType,evidence,legalElementResultIds:[],typicalCases:[]});generatorVisible.value=false;const completed=await waitForJob(()=>getReportJob(caseId.value,created.requestId));await loadReports(caseId.value);if(completed)ElMessage.success('报告生成完成');else ElMessage.info('报告仍在后台生成')}catch(error){ElMessage.error(error.message)}finally{generating.value=false}}
function statusLabel(value){return({GENERATING:'生成中',DRAFT:'草稿',REVIEWING:'复核中',FINAL:'已定稿',FAILED:'生成失败'})[value]||value}function statusClass(value){return({GENERATING:'b-blue',DRAFT:'b-gray',REVIEWING:'b-gold',FINAL:'b-green',FAILED:'b-red'})[value]||'b-gray'}function formatTime(value){return value?new Date(value).toLocaleString('zh-CN'):'-'}
</script>

<style scoped>
.report-editor textarea{width:100%;padding:10px 12px;border:1px solid var(--border);border-radius:8px;line-height:1.8}.report-text{min-height:90px;padding:12px 14px;white-space:pre-wrap;line-height:1.9;color:#46566b;background:#fbfcfe;border:1px solid var(--border);border-radius:8px}.small-modal{width:min(92vw,480px)}
.report-sources{max-height:150px;overflow:auto;border:1px solid var(--border);border-radius:8px;padding:6px 10px}.report-sources>label{display:flex;align-items:center;gap:8px;padding:6px 2px}.report-sources>label span{flex:1}.report-sources small{color:var(--muted)}
</style>
