package com.lexpro.lexprobackend.recommendation.domain;

import java.time.LocalDate;
import java.time.OffsetDateTime;

public record TypicalCaseRecord(
        long typicalCaseId,
        String externalCaseId,
        String caseNumber,
        String title,
        String caseCause,
        String caseCauseFullJson,
        String caseType,
        String country,
        String region,
        String court,
        String courtLevel,
        String docType,
        String disputeFocusJson,
        LocalDate judgmentDate,
        String procedure,
        String applicableLawJson,
        String caseLevel,
        String sourceName,
        String sourceFile,
        String sourceUrl,
        String keywordsJson,
        String embeddingModelName,
        String embeddingModelVersion,
        OffsetDateTime embeddedAt,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        String content,
        String fact,
        String summary,
        String prosecutorialProcess,
        String adjudicationResult,
        String reasoning,
        String guidingSignificance,
        boolean favorite
) {}
